ENV['SENDGRID_USER'] = 'your sendgrid username'
ENV['SENDGRID_PASSWORD'] = 'your sendgrid password'
ENV['SENDGRID_DOMAIN'] = 'your sendgrid domain'
ENV['YAHOO_APP_ID'] = 'your app ID for Yahoo! GeoPlanet'
ENV['RAILS_COOKIE_TOKEN'] = 'at least 30 random hex digits'
ENV['EMAIL_BYPASS_USER'] = 'a developer email to use in development'
ENV['RINGSAIL_HOST'] = 'hostname where ringsail is installed'
